ARG JDK=25.0.3_9

FROM docker.io/eclipse-temurin:${JDK}-jdk-alpine AS build

ARG UID=1000
ARG GID=1000
ENV SPRING_PROFILES_ACTIVE=ci

RUN addgroup -g ${GID} server && adduser -u ${UID} -G server -D server -h /home/server

WORKDIR /home/server

USER server

COPY --chown=server:server ../api-client api-client
COPY --chown=server:server ../libs.versions.toml libs.versions.toml
COPY --chown=server:server ../common common
COPY --chown=server:server ../build-logic build-logic
COPY --chown=server:server ../backend backend

WORKDIR backend

RUN ["./gradlew", "assemble"]
RUN mkdir -p build/test-results build/jacoco && chown -R server:server build
CMD ["./gradlew", "test", "integrationTest", "migrationTest", "--console=plain", "jacocoTestReport"]

FROM docker.io/eclipse-temurin:${JDK}-jre-alpine
ARG UID=1000
ARG GID=1000

EXPOSE 8080
EXPOSE 5005

RUN addgroup -g $GID server && adduser -u $UID -G server -D server -h /home/server

COPY --chown=server:server --from=build /home/server/backend/build/libs/backend-*.jar /home/server/server.jar

USER server


