spring:
  application:
    name: "backend"
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: "localhost"
      password: "developmentpassword"
      port: 6379
  session:
    data:
      redis:
        namespace: "spring:session"
        # we might need this if we want to sync updates from Emporix into user sessions
        # enabling this however locks us out of redis clustering, see https://docs.spring.io/spring-session/reference/configuration/redis.html#choosing-between-regular-and-indexed
        # ideally we go for indexed without clustering
        # repository-type: indexed
    #        flush-mode: immediate
    # anonymous tokens only can be refreshed for 24 hours and live for 1 hour
    # since we don't refresh the token if the user does not log in, we require
    # a shorter session refresh time of 12 hours; you could extend that if
    timeout: 86280s
backend:
  cors-domains: [ ]
  emporix-api:
    timeout-millis: 55000 # this must be shorter than the redis lock timeout
    oauth:
      refresh-margin-in-seconds: 120
      storefront:
        # anonymous tokens only can be refreshed for 24 hours and live for 1 hour
        client-id: "EsEnhsDGx2mC89leN5KyymlGcMj9FRhueAaKI8vE5l2b284f"
        client-scopes:
          - "tenant=${backend.tenant}"
      emporix:
        client-id: "XH5ej9Tpdlg1SaI1vosMSowEYyvsTMsz1iGIi3B3qaYKIVBU"
        client-scopes:
          - "iam.group_read"
          - "customer.customer_read"
          - "tenant=${backend.tenant}"

  users:
    actuator:
      login: "actuator"
  tenant: "fyaycff1"

server:
  servlet:
    session:
      cookie:
        http-only: true