spring:
  application:
    name: "backend"
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: "localhost"
      password: "developmentpassword"
      port: 6379
  session:
    data:
      redis:
        namespace: "spring:session"
        # we might need this if we want to sync updates from emporix into user sessions
        # enabling this however locks us out of redis clustering, see https://docs.spring.io/spring-session/reference/configuration/redis.html#choosing-between-regular-and-indexed
        # repository-type: indexed
backend:
  cors-domains: [ ]
  emporix-api:
    timeout-millis: 55000 # this must be shorter than the redis lock timeout
    oauth:
      # Emporix API
      refresh-margin-in-seconds: 30
      client-id: "XH5ej9Tpdlg1SaI1vosMSowEYyvsTMsz1iGIi3B3qaYKIVBU"
      client-scopes:
        tenant: "${backend.tenant}"
  users:
    actuator:
      login: "actuator"
  tenant: "fyaycff1"