backend:
  emporix-api:
    oauth:
      storefront:
        client-secret: "developmentpassword"
      emporix:
        client-secret: "developmentpassword"
  users:
    actuator:
      password: "developmentpassword"