inputs:
  directory:
    description: 'in which directory to run'
    required: true
runs:
  using: "composite"
  steps:
  - name: "Set up Docker Compose"
    # pin to hash to avoid attacks changing tags to vulnerable version
    uses: "docker/setup-compose-action@4eb059ff7f16592f9c84d5ca339c53cb7c5064e2"
  - name: "Setup mounted volumes"
    shell: "bash"
    run: "mkdir -p container/build/test-results container/build/jacoco && sudo chown -R 1000:1000 container"
    working-directory: "${{ inputs.directory }}"
  - name: "Run tests"
    shell: "bash"
    run: "docker compose -f docker-compose-ci.yml build && docker compose -f docker-compose-ci.yml up --exit-code-from=application --abort-on-container-exit"
    working-directory: "${{ inputs.directory }}"